
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.undo.UndoManager;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author alu20924612v
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    File fileRead;
    File fileWrite;
    UndoManager undoManager;

    public MainFrame() {
        initComponents();
        initVariables();

    }

    private void initVariables() {
        fileRead = null;
        fileWrite = null;
        textAreaDisplay.setText("");
        undoManager = new UndoManager();
        
        textAreaDisplay.getDocument().addUndoableEditListener(undoManager);
        

    }

    private void writeOnFile() throws IOException {
        PrintWriter output = null;

        try {
            output = new PrintWriter(new FileWriter(fileWrite));

            output.write(textAreaDisplay.getText());

        } finally {
            if (output != null) {
                output.close();
            }
        }

    }

    private void readFromFile() throws IOException {
        BufferedReader input = null;
        try {
            input = new BufferedReader(new FileReader(fileRead));
            String line = "";
            while ((line = input.readLine()) != null) {
                textAreaDisplay.setText(textAreaDisplay.getText() + line + "\n");
            }
        } finally {
            if (input != null) {
                input.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        btnSave2 = new javax.swing.JButton();
        btnOpenFile2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaDisplay = new javax.swing.JTextArea();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuSave = new javax.swing.JMenu();
        btnFileNew = new javax.swing.JMenuItem();
        btnOpenFIle = new javax.swing.JMenuItem();
        btnSave = new javax.swing.JMenuItem();
        btnExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        btnUndo = new javax.swing.JMenuItem();
        btnRedo = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setRollover(true);

        btnSave2.setText("Guardar");
        btnSave2.setFocusable(false);
        btnSave2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSave2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnSave2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSave2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnSave2);

        btnOpenFile2.setText("Cargar");
        btnOpenFile2.setFocusable(false);
        btnOpenFile2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnOpenFile2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnOpenFile2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFile2ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnOpenFile2);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        textAreaDisplay.setColumns(20);
        textAreaDisplay.setRows(5);
        jScrollPane1.setViewportView(textAreaDisplay);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        menuSave.setText("File");

        btnFileNew.setText("New");
        btnFileNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFileNewActionPerformed(evt);
            }
        });
        menuSave.add(btnFileNew);

        btnOpenFIle.setText("Open file");
        btnOpenFIle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFIleActionPerformed(evt);
            }
        });
        menuSave.add(btnOpenFIle);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        menuSave.add(btnSave);

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        menuSave.add(btnExit);

        jMenuBar1.add(menuSave);

        jMenu3.setText("Edit");

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });
        jMenu3.add(btnUndo);

        btnRedo.setText("Redo");
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });
        jMenu3.add(btnRedo);

        jMenuBar1.add(jMenu3);

        jMenu6.setText("About");
        jMenu6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu6ActionPerformed(evt);
            }
        });

        jMenuItem3.setText("Help");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem3);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnFileNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFileNewActionPerformed
        int n= JOptionPane.showConfirmDialog(this, "Do you want to delete the current text?",
                        "Remove test?", JOptionPane.YES_NO_OPTION);
        if (n == 0) {
           initVariables(); 
        }
        
    }//GEN-LAST:event_btnFileNewActionPerformed

    private void btnSave2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSave2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "text file", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            fileWrite = chooser.getSelectedFile();

            try {
                writeOnFile();
            } catch (IOException ex) {

            }
        }
    }//GEN-LAST:event_btnSave2ActionPerformed

    private void btnOpenFile2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFile2ActionPerformed
        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
                "text file", "txt");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {

            fileRead = chooser.getSelectedFile();

            try {
                readFromFile();
            } catch (IOException ex) {

            }
        }
    }//GEN-LAST:event_btnOpenFile2ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        btnSave2ActionPerformed(evt);

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnOpenFIleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFIleActionPerformed
        btnOpenFile2ActionPerformed(evt);
    }//GEN-LAST:event_btnOpenFIleActionPerformed

    private void jMenu6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu6ActionPerformed
        JOptionPane.showConfirmDialog(this, "The program is an exercise for the programming subject IES EL CAMINAS", "", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenu6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        JOptionPane.showConfirmDialog(this, "The program is an exercise for the programming subject IES EL CAMINAS", "", JOptionPane.OK_OPTION);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        undoManager.undo();
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        undoManager.redo();
    }//GEN-LAST:event_btnRedoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnFileNew;
    private javax.swing.JMenuItem btnOpenFIle;
    private javax.swing.JButton btnOpenFile2;
    private javax.swing.JMenuItem btnRedo;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JButton btnSave2;
    private javax.swing.JMenuItem btnUndo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenu menuSave;
    private javax.swing.JTextArea textAreaDisplay;
    // End of variables declaration//GEN-END:variables

}
